(ManagerV2): issue on firmware update reset connnection
valpinkman/lld-v2 pull request #184
Opened 2020-02-05 16:39 UTC by LFBarreto

While on firmware update on the bootloader phase that asks you to disconnect and reconnect your device, the manager state was resetted thus looping beetween the osu download and the device connection.

![localhost_8080_webpack_index html](https://user-images.githubusercontent.com/11752937/73861797-d8756a80-483d-11ea-9234-d2d5e516a069.png)

The device connection state is now locked on firmware update and controlled by the manager dashboard component.

### Type

Bug Fix

### Context

maybe connected to LL-2178

### Parts of the app affected / Test plan

ManagerV2 mainly on firmware updates

2020-02-05 16:59 UTC, valpinkman commented on src/renderer/screens/manager/FirmwareUpdate/index.js
> +  onUpdateStart: () => void,
are they always required ? Are you sure there are no other context in which onUpdateStart and onUpdateStop will not get passed ?

2020-02-05 17:04 UTC, valpinkman commented on src/renderer/screens/manager/FirmwareUpdate/index.js
> +  onUpdateStart: () => void,
My bad I thought it was the Modal

2020-02-05 17:04 UTC, valpinkman approved these changes

2020-02-05 18:04 UTC, gre requested changes

2020-02-05 18:04 UTC, gre commented on src/renderer/components/ManagerConnect/index.js
> +  }
ok, i apologize that this was not existing yet. unfortunately the current implementation is going to create bugs (could double call onSuccess. not a good idea to call in render step). please look and try to get in this implementation instead: https://github.com/LedgerHQ/lld-v2/blob/poc-device-connect/src/renderer/components/DeviceAction/index.js#L195

**OR maybe we should just get this in the PR #127**

2020-02-05 18:04 UTC, gre commented on src/renderer/screens/manager/Dashboard.js
> +  const currentDevice = useSelector(getCurrentDevice);
as this component seems to be connect, I would suggest instead to just have:

```
resetLock = useSelect(aSelectorThatCheckIfFirmwareUpdateModalIsOpened)
```

that would simplify some code below.

2020-02-05 18:11 UTC, gre commented
@LFBarreto let's work together tomorrow to see if we can backport this work directly inside the DeviceAction rework PR (#127) because things will be simpler there. also i think my comment regarding detecting a firmware update by modal presence could work but to be double check ;)

2020-02-06 13:47 UTC, gre commented
integrated in https://github.com/LedgerHQ/lld-v2/pull/127/commits/36ea62b95e324a7bb0f3bcf7d06f33461a1c4cb0
in context of https://github.com/LedgerHQ/lld-v2/pull/127

2020-02-06 15:00 UTC, closed without merging

2020-02-06 15:01 UTC, gre commented
there are other changes in this PR unrelated to firmware update, please resubmit them in another PR @LFBarreto