bump libs including Electron 8
valpinkman/lld-v2 pull request #186
Opened 2020-02-05 19:40 UTC by gre

everything seems to be fine with Electron 8 but app can be tested a bit more.

This includes a bump of live-common that also fixes the "uninstall" for 1.3.1 on the failsafe mode of Manager v2.

2020-02-06 08:53 UTC, IAmMorrow approved these changes

2020-02-06 15:04 UTC, valpinkman approved these changes

2020-02-06 16:47 UTC, Arnaud97234 requested changes
USB is not working on Linux, could be because of electron-builder that is not up to date for electron 8.

On all platforms the following error is displaying during `yarn` process.
```
Error: Could not detect abi for version 8.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
        at getAbi (/Users/aulric/Workspace/repos/lld-v2/node_modules/node-abi/index.js:30:9)
        at module.exports (/Users/aulric/Workspace/repos/lld-v2/node_modules/prebuild-install/rc.js:73:57)
        at Object.<anonymous> (/Users/aulric/Workspace/repos/lld-v2/node_modules/prebuild-install/bin.js:9:25)
        at Module._compile (internal/modules/cjs/loader.js:955:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
        at Module.load (internal/modules/cjs/loader.js:811:32)
        at Function.Module._load (internal/modules/cjs/loader.js:723:14)
        at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
        at internal/main/run_main_module.js:17:11
```

2020-02-12 13:07 UTC, IAmMorrow approved these changes

2020-02-12 16:55 UTC, gre commented
@Arnaud97234 you can retest. normally the node-abi problem is solved.

2020-02-18 17:50 UTC, Arnaud97234 approved these changes

2020-02-18 17:53 UTC, merged