LL-2196 scroll to top on page change
valpinkman/lld-v2 pull request #206
Opened 2020-02-10 17:27 UTC by valpinkman

scroll to top on page change

### Type

Feat

### Context

LL-2196

2020-02-10 18:11 UTC, Arnaud97234 approved these changes

2020-02-10 18:15 UTC, gre requested changes

2020-02-10 18:15 UTC, gre commented on src/renderer/hooks/useScrollToTopOnMount.js
> +    console.log("scrolling to top bitch");
:wtf:

2020-02-11 10:20 UTC, valpinkman commented on src/renderer/hooks/useScrollToTopOnMount.js
> +    console.log("scrolling to top bitch");
oops forgot to remove dead code

2020-02-11 14:14 UTC, gre approved these changes

2020-02-11 14:14 UTC, merged